### ISSUE TITLE
Can't replicate regex find and replace example

### ISSUE THREAD

**Issue by kerryj89** [caddis/streeng#10]
Firstly, thanks for the great add-on!

I am however having an issue with the regex function.  My EE version is 2.10.1 and I tried Streeng 1.5.3 and 1.9.0 but it only outputs the text exactly as is between the tag pairs.

The only code that exists in my test template:

```
{exp:streeng find="http:\/\/(.*).com" replace="https://www.caddis.co"}
    https://caddisint.com
{/exp:streeng}
```

Is this snippet still working for you or is there something that I forgot to enable?

Thanks,
-Kerry

**Comment by leigeber** [comment]
Hey Kerry, there is actually a typo in that example, sorry about that. If the find value has https instead of http the replacement works as it should on my end. Does it work on your end with that modification?

**Comment by kerryj89** [comment]
Oh, I'm embarrassed that I didn't even catch that.

Anyway, I would like to use your add-on for a slightly complex Regex.  I can't seem to get the pattern right with Streeng, but I got it working with Low Replace.  Ideally I'd just stick to using your module only.  Can you replicate the following pattern using your add-on?

```
{exp:low_replace find="https?\:\/\/([^\/?#]+)(?:[\/?#]|$)" replace="" regex="yes"}
	https://www.instagram.com/test/
{/exp:low_replace}
```

Result:  test/

I might be overlooking something again...

Thanks,
-Kerry

**Comment by leigeber** [comment]
Makes sense. Since Streeng splits on the pipe character by default for multiple find targets and you have that in your RegEx you need to change the explode character by adding something like explode="%" to the tag pair.

**Comment by kerryj89** [comment]
Ah, I see.  I don't know how to mark this as solved but I have no more issues.  Thanks again!
