### ISSUE TITLE
"url" option should encode spaces as "%20"

### ISSUE THREAD

**Issue by jkorff** [caddis/streeng#12]
I am using Streeng to urlencode text for an email.

Since Streeng currently uses the PHP function "urlencode", it encodes spaces as plus signs.

I recommend changing this to use "rawurlencode" so that spaces are encoded as "%20".

See PHP manual: http://php.net/manual/en/function.rawurlencode.php

**Comment by leigeber** [comment]
Thanks for the suggestion, makes total sense but since it would be a major breaking change I think we would be better off adding a `rawurl` parameter. Would that seem to make sense to you?

**Comment by jkorff** [comment]
Hi Michael,

sure, that's an even better option. Thank you!

Regards,
Jens

**Comment by leigeber** [comment]
This has been resolved with the latest release. Ended up allowing "raw" as a value to the existing url parameter, which was ultimately the cleanest solution.

https://github.com/caddis/streeng/releases/tag/1.10.0
