### ISSUE TITLE
Streeng leaving three dots when using words parameter

### ISSUE THREAD

**Issue by frshjb373** [caddis/streeng#13]
For some reason some of the entries have 3 dots that are trailing end of content when using the following: 

`{exp:streeng words="50"}{profile_team_members:team_profile_content}{/exp:streeng}`

Content field is a wygwam field in EE3. Any idea what the issue is?

![screen shot 2017-01-19 at 10 46 25 am](https://cloud.githubusercontent.com/assets/7178139/22120444/9285b26c-de34-11e6-8cdc-b2d88fd21f95.png)

**Comment by thechrisroberts** [comment]
Streeng automatically appends an ellipsis when truncating text. To remove, add the attribute append=""
