### ISSUE TITLE
Playing with emails

### ISSUE THREAD

**Issue by noor8380** [caddis/streeng#7]
It would be great if Streeng does some manipulation to email ids.. so that it doesn't show the whole email. e.g. na**@*****.com for name@gmail.com

**Comment by noor8380** [comment]
na** @ *** **.com

**Comment by leigeber** [comment]
Thanks for the suggestion. Would this be for emails that are linked to try and prevent spam or just for redacting plaintext email addresses? There are a couple addons that specifically try to prevent spam from embedded email addresses on Devotee, not sure if you've seen those?

**Comment by noor8380** [comment]
I guess, I overlooked the regular expression part of Streeng. That combined with find and replace does the job. You guys got it already covered! Yes, Snaptcha works great for preventing spam :)

**Comment by leigeber** [comment]
Glad to hear!
