### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ricklecoat** [caddis/streeng#8]
I'm looking at using Streeng to replace a trio of other string manipulation add-ons -- Low Replace, Excerpt and Stringy. It appears that Streeng can do everything that these others can do (yay!) with the exception of a couple of handy features that [Stringy](https://devot-ee.com/add-ons/stringy) has that Streeng seems not to. Specifically:
* **{exp:stringy:shuffle}** (shuffling the characters between the tag pair);
* **{exp:stringy:length}** (returns the number of characters between the tag pair);
* **{exp:stringy:numberformat decimals="0" dec_point="." thousands_sep=","}** (optionally adds decimal point and trailing zeros, define characters for decimal point and thousands separator).

Is there any chance of incorporating those features into Streeng somehow so that I can have a single string-manipulation tool that handles everything? That would be great. Thanks.

**Comment by leigeber** [comment]
Hello there. I think length is a great suggestion, we can get that added by allowing count="*" or something like that with the existing syntax. Can you give me the use case for shuffle? Not sure I'm seeing the value of adding that one.

As for the mathematical operations, I'm not sold on us doing that, given that Streeng is based around a single tag pair with parameters. We have all that logic in https://github.com/caddis/math and it would really start muddying up Streeng.

**Comment by ricklecoat** [comment]
Hi there, Yes, I entirely take your point about doubling up with Math, so that's dealt with. And *shuffle* was always a fringe use-case, so yes, ignore that by all means. If I ever build an anagrams site I'll come back to you. Interesting about making *length* part of *count* -- tbh, *count* and *splits* are the two parameters of Streeng that I don't quite get my head around very well, at least not from the documentation. Can you explain how they work? I assume that the 'supplied string' is the parameter's value ("|" in the example) so *count* will find how many times that string/value appears in the text between the tag pair, right? But I'm still a bit confused about *splits* and what result that returns. Also, if you use *count* as a way of implementing Stringy's *length* option in the way you describe above, would that not (assuming that I'm correctly understanding how to use *count*) simply count how many asterisks appear in the text? (Sorry to be dense).

**Comment by leigeber** [comment]
Splits would essentially explode the string on that character and let you know how many pieces there are after the split. Count would just look for that character so essentially splits is count + 1 in essence. You are correct about it counting the * character unless we used that as a reserved pattern which may not be the best thing to do. Allowing count to support regex could be an option. Any thought on that?

**Comment by leigeber** [comment]
Streeng 1.8 has been published with a count="ALL" option to count all characters. Hope this helps you consolidate addons.

**Comment by ricklecoat** [comment]
Great stuff, thanks!
